---
- name: download csf
  get_url: url=https://download.configserver.com/csf.tgz dest=/root/csf.tgz

- name: extract csf
  unarchive: src=/root/csf.tgz dest=/root copy=no

- name: install build env
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - perl
    - make
    - gcc
    - unzip

- name: prepare perl
  shell: curl -L https://cpanmin.us | perl - --sudo App::cpanminus

- name: install csf prerequisites
  cpanm: name={{item}}
  with_items:
    - Bundle::LWP
    - HTML::Strip

- name: install csf
  shell: /root/csf/install.sh chdir=/root/csf/

- name: remove archive
  file: path=/root/csf.tgz state=absent

- name: remove folder
  file: path=/root/csf/ state=absent

- name: add the necessary file j2 templates for ssh and csf with editable variables to respective folders 
  template:
    src: templates/{{ item.src }}
    dest: "{{ item.dest }}"
  with_items:
    - { src: sshd_config.conf.j2,     dest: "/etc/ssh/sshd_config" }
    - { src: csf.conf.j2,  dest: "/etc/csf/csf.conf" }

- name: restart ssh
  service: name=sshd state=restarted

- name: add servercheck script
  template: src=servercheck.pl dest=/etc/csf/servercheck.pl

- name: finished
  debug: msg="Test the firewall, then take CSF out of testing mode (from csf.conf). Run servercheck.pl to check remaining hardening tasks."

- name: copy custom iptables rules to csfpre.sh
  template:
    src: templates/{{ item.src }}
    dest: "{{ item.dest }}"
  with_items:
    - { src: iptables-csfpre.j2,     dest: "/etc/csf/csfpre.sh" }

- name: Start and enable csf service
  systemd: daemon_reload=yes name=csf.service state=started enabled=yes

- name: Restart csf to effect custom rules in csfpre.sh
  command: csf -r