---

# tasks file for rkhunter
- name: install rkhunter
  yum:
    name: rkhunter
    state: present
  when: ansible_os_family == "RedHat"

- name: rkhunter update
  command: rkhunter --propupd

- name: template rkhunter.conf
  template: src=rkhunter.conf.j2 dest=/etc/rkhunter.conf mode=0640
  
- name: deploy rkhunter sysconfig
  template: src=rkhunter.j2 dest=/etc/sysconfig/rkhunter mode=0640
- name: rkhunter update
  command: rkhunter --propupd